
services:
  # Override PHP service for development
  php:
    volumes:
      - ./:/var/www/html:cached
    environment:
      - APP_ENV=dev
      - APP_DEBUG=1
      - PHP_IDE_CONFIG=serverName=symfony

  # Override Nginx service for development
  nginx:
    ports:
      - "8080:80"
