
services:
  php:
    build:
      context: ./docker/php
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    environment:
      - APP_ENV=dev
      - APP_DEBUG=1
    ports:
      - "9000:9000"

  nginx:
    image: nginx:alpine
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - php
